[package]
name = "monkey-interpreter"
version = "0.1.0"
authors = ["Luccas Mateus de Medeiros Gomes <luccasmmg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8" #Needed for the REPL
